# Generated by Django 5.0.4 on 2024-07-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_college_item_elementary_item_secondary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vocational_trade_course',
        ),
    ]
